[theme]
primaryColor = "#D95F3B"
backgroundColor = "#F5F2EE"
secondaryBackgroundColor = "#EDEAE5"
textColor = "#1C1C1C"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false